version: '3.8'
services:
  redis:
    image: redis:7.2
    container_name: redis-matching
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
  mongo:
    image: mongo:6.0
    container_name: mongo-matching
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight-matching
    ports:
      - "5540:5540"
    restart: always
volumes:
  redis_data:
  mongo_data:
